theme = "mellow"

[editor]
rulers = [80, 100, 120]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.auto-pairs]
#'(' = ')'
#'{' = '}'
#'[' = ']'
#'"' = '"'
#'`' = '`'
'“' = '”'
'‘' = '’'
'«' = '»'

[editor.indent-guides]
render = true

