" Appearance
set guifont=Iosevka\ 10
set guioptions-=T  " disable toolbar
set guioptions-=m  " disable menu
set guioptions-=rL  " disable scrollbars

" Default window size
set columns=128
set lines=60
